version: '3.9'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './sp7-stats/config/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './sp7-stats/:/var/www/:ro'
      - './sp7-stats/config/fullchain.pem:/etc/letsencrypt/live/sp7-stats/fullchain.pem:ro'
      - './sp7-stats/config/privkey.pem:/etc/letsencrypt/live/sp7-stats/privkey.pem:ro'
    networks:
      - nginx
    depends_on:
      - php

  php:
    build:
      context: ./
      target: back_end
    env_file:
      ./env
    volumes:
      # CHANGE THIS:
      # Location to the place where all of your access.log files are located.
      # Make sure the web server has read permissions to all the files in this folder.
      - './access-logs/:/home/specify/access-logs/'
      - './sp7-stats/:/var/www/:ro'
      - 'working-dir:/home/specify/working-dir/'
    networks:
      - nginx

networks:
  nginx:

volumes:
  database:
  working-dir:
